module.exports = {
  rules: {
    'alpha-value-notation': 'number',
    'at-rule-empty-line-before': 'always',
    'color-function-notation': 'modern',
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'comment-no-empty': true,
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-block-single-line-max-declarations': 1,
    'declaration-no-important': true,
    'font-family-name-quotes': 'always-where-recommended',
    'function-url-quotes': 'never',
    'import-notation': 'url',
    'length-zero-no-unit': true,
    'media-feature-name-no-unknown': true,
    'no-descending-specificity': true,
    'no-duplicate-selectors': true,
    'no-invalid-position-at-import-rule': true,
    'no-unknown-animations': true,
    'property-no-unknown': true,
    'rule-empty-line-before': 'always',
    'selector-class-pattern': null,
    'selector-type-case': 'lower',
    'shorthand-property-no-redundant-values': true,
    'value-keyword-case': ['lower', { camelCaseSvgKeywords: true }],
  },
};
